// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndrzotjilfbpfdvuqroe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcnpvdGppbGZicGZkdnVxcm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDY2MDcsImV4cCI6MjA2MjEyMjYwN30.RQqTEnagyEqlr22WYTmc9pMXhssKUxjb4S3bm_foMqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);